apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://jeffrinjojo1_db_user:wk4OXPEPMXbvPJ5s@cluster0.bgowo9e.mongodb.net/learn_mern?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "my_super_secret_bouncer_code"
  RAZORPAY_KEY_ID: "rzp_test_yourkeyid"
